### PR TITLE
Fu 71 fixes

### PR DESCRIPTION
**Pull request by bihu1**

### CODE REVIEW

**Comment by golbi** [comment]
This PL mixes FU-72 impl with FU-71 fixes. Can this be corrected?

**Comment by bihu1** [comment]
I've create this branch from FU-72, cause I've needed changes form that branch. You merged FU-72, so now it should not be mixed?

**Comment by golbi** [comment]
FU-72 was not merged I believe

**Comment by golbi** [comment]
If so pls work on FU-72 so that we can merge it and we will come back to it (hopefully diff should be smaller?)

**Comment by golbi** [comment]
closing in line with the above comment

**Pull request closed without merging**
